#!/usr/bin/env bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

SCRIPT_DIR=$(dirname $0)
SCRIPT_DIR=$(readlink -e ${SCRIPT_DIR})

CRUCIBLE_INSTALL_SRC="https://raw.githubusercontent.com/perftool-incubator/crucible/master/crucible-install.sh"

# configure SSH for loopback connectivity
apt install openssh-server
systemctl start sshd
ssh-keygen -t ed25519 -q -f /root/.ssh/id_ed25519 -N ""
bash -c "cat /root/.ssh/id_ed25519.pub > /root/.ssh/authorized_keys"
chmod 600 /root/.ssh/authorized_keys
ssh -o StrictHostKeyChecking=no localhost echo "password-less root login over ssh works"

# condition environment for crucible
mkdir -p /etc/sysconfig

if pushd ~/ > /dev/null; then
    wget ${CRUCIBLE_INSTALL_SRC}
    chmod +x ./crucible-install.sh
    ./crucible-install.sh --client-server-registry --client-server-registry dir:/home/crucible-containers/client-server --name nobody --email nobody@nobody.nobody.com --verbose
    RC=$?

    popd > /dev/null
else
    echo "ERROR: Could not pushd to ~/"
    exit 1
fi

exit ${RC}
