name: "install crucible"
description: "Install Crucible for use by various crucible-ci actions and/or workflows"
inputs:
  ci_target:
    description: "Which Crucible component to target for integration testing"
    required: false
    default: "none"
  ci_target_dir:
    description: "Where is the Crucible component to target located"
    required: false
    default: "none"
  ci_endpoint:
    description: "Which rickshaw endpoint to exercise"
    required: false
    default: "remotehosts"
  ci_controller:
    description: "Whether a CI built controller should be used or not"
    required: false
    default: "no"
  controller_tag:
    description: "A controller tag to pull from the ci controller repository"
    required: false
    default: "none"
  release_tag:
    description: "A Crucible release tag/version to tell the installer to use"
    required: false
    default: "upstream"
runs:
  using: "composite"
  steps:
    - run: sudo ${{ github.action_path }}/install-crucible.sh --run-environment github --ci-target ${{ inputs.ci_target }} --ci-target-dir ${{ inputs.ci_target_dir }} --ci-endpoint ${{ inputs.ci_endpoint }} --ci-controller ${{ inputs.ci_controller }} --controller-tag ${{ inputs.controller_tag }} --release-tag ${{ inputs.release_tag }}
      shell: bash
