#!/usr/bin/env bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

SCRIPT_DIR=$(dirname $0)
SCRIPT_DIR=$(readlink -e ${SCRIPT_DIR})

. ${SCRIPT_DIR}/base

CI_RUN_ENVIRONMENT="standalone"

CI_CLEAN_ENVIRONMENT="yes"

longopts="run-environment:,clean-environment:"
opts=$(getopt -q -o "" --longoptions "${longopts}" -n "$0" -- "$@")
if [ ${?} -ne 0 ]; then
    echo "ERROR: Unrecognized option specified: $@"
    exit 1
fi
eval set -- "${opts}"
while true; do
    case "${1}" in
        --clean-environment)
            shift
            CI_CLEAN_ENVIRONMENT="${1}"
            shift
            ;;
        --run-environment)
            shift
            CI_RUN_ENVIRONMENT="${1}"
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "ERROR: Unexpected argument [${1}]"
            shift
            break
            ;;
    esac
done

# validate inputs
validate_ci_run_environment
validate_ci_clean_environment

if [ "${CI_CLEAN_ENVIRONMENT}" == "yes" ]; then
    header="Clean CI environment"
    start_github_group "${header}"
    echo -e "*** ${header} ***\n"
    stop_github_group

    header="Stopping Crucible Services"
    start_github_group "${header}"
    echo -e "### ${header} ###\n"
    echo
    crucible stop es
    crucible stop httpd
    crucible stop redis
    stop_github_group

    header="Removing podman resources (containers and images)"
    start_github_group "${header}"
    echo -e "### ${header} ###\n"
    echo
    cmd="podman stop --all"
    echo "${cmd}"
    ${cmd}
    cmd="podman rm --all"
    echo "${cmd}"
    ${cmd}
    cmd="buildah rm --all"
    echo "${cmd}"
    ${cmd}
    cmd="podman rmi --all"
    echo "${cmd}"
    ${cmd}
    stop_github_group

    header="Removing Crucible installed/created files"
    start_github_group "${header}"
    echo -e "### ${header} ###\n"
    echo
    cmd="rm -Rfv /opt/crucible* /var/lib/crucible* /etc/sysconfig/crucible  /root/.crucible /etc/profile.d/crucible_completions.sh /home/crucible-containers"
    echo "${cmd}"
    ${cmd}
    stop_github_group
else
    header="Environment cleaning disabled"
    start_github_group "${header}"
    echo -e "*** ${header} ***\n"
    stop_github_group
fi

header="Determine stage 1 exit status"
start_github_group "${header}"
echo -e "*** ${header} ***\n"

stage1_exit_status_file="/tmp/run-ci-stage1-exit-status"
if [ -e "${stage1_exit_status_file}" ]; then
    read stage1_exit_status < ${stage1_exit_status_file}
    rm ${stage1_exit_status_file}

    if [ -z "${stage1_exit_status}" ]; then
        echo "ERROR: Read an empty stage 1 exit status from ${stage1_exit_status_file}"
    else
        echo "Read stage 1 exit status as ${stage1_exit_status} from ${stage1_exit_status_file}"
        exit ${stage1_exit_status}
    fi
else
    echo "ERROR: Could not find stage 1 exit status because ${stage1_exit_status_file} does not exist"
fi

exit 1

stop_github_group
