#!/usr/bin/env bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

SCRIPT_DIR=$(dirname $0)
SCRIPT_DIR=$(readlink -e ${SCRIPT_DIR})

. ${SCRIPT_DIR}/base

CRUCIBLE_INSTALL_SRC="https://raw.githubusercontent.com/perftool-incubator/crucible/master/crucible-install.sh"
CI_TARGET="none"
CI_TARGET_DIR="none"
CI_RUN_ENVIRONMENT="standalone"
CI_ENDPOINT="remotehost"

REGISTRY_TLS_VERIFY="true"

longopts="ci-target:,ci-target-dir:,run-environment:,ci-endpoint:"
opts=$(getopt -q -o "" --longoptions "${longopts}" -n "$0" -- "$@")
if [ ${?} -ne 0 ]; then
    echo "ERROR: Unrecognized option specified: $@"
    exit 1
fi
eval set -- "${opts}"
while true; do
    case "${1}" in
        --ci-endpoint)
            shift
            CI_ENDPOINT="${1}"
            shift
            ;;
        --run-environment)
            shift
            CI_RUN_ENVIRONMENT="${1}"
            shift
            ;;
        --ci-target)
            shift
            CI_TARGET="${1}"
            shift
            ;;
        --ci-target-dir)
            shift
            CI_TARGET_DIR="${1}"
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "ERROR: Unexpected argument [${1}]"
            shift
            break
            ;;
    esac
done

# validate inputs
validate_ci_run_environment
validate_ci_endpoint

# configure SSH for loopback connectivity
start_github_group "Configure loop SSH access"
apt install openssh-server
systemctl start sshd
ssh-keygen -t ed25519 -q -f /root/.ssh/id_ed25519 -N ""
bash -c "cat /root/.ssh/id_ed25519.pub > /root/.ssh/authorized_keys"
chmod 600 /root/.ssh/authorized_keys
ssh -o StrictHostKeyChecking=no localhost echo "password-less root login over ssh works"
stop_github_group

# ensure endpoint availability
case "${CI_ENDPOINT}" in
    k8s)
        start_github_group "Configure k8s endpoint"

        # fixup some microk8s dependencies before installing it
        update-alternatives --set iptables /usr/sbin/iptables-legacy
        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

        snap install microk8s --classic
        microk8s status --wait-ready

        printf "#%s/bin/bash\n\nmicrok8s kubectl \$@\n" "!" > /usr/local/bin/kubectl
        chmod +x /usr/local/bin/kubectl

        microk8s enable registry
        CONTAINER_REGISTRY="localhost:32000/client-server"
        REGISTRY_TLS_VERIFY="false"

        stop_github_group
        ;;
    remotehost)
        start_github_group "Configure remotehost endpoint"

        CONTAINER_REGISTRY="dir:/home/crucible-containers/client-server"

        stop_github_group
        ;;
esac

# condition environment for crucible
start_github_group "Create /etc/sysconfig"
mkdir -pv /etc/sysconfig
stop_github_group

start_github_group "Install Crucible"
if pushd ~/ > /dev/null; then
    INSTALLER_PATH="./crucible-install.sh"
    INSTALLER_ARGS=""
    if [ -n "${CI_TARGET}" -a -n "${CI_TARGET_DIR}" -a "${CI_TARGET}" == "crucible" ]; then
        INSTALLER_PATH="${CI_TARGET_DIR}/crucible-install.sh"
        INSTALLER_ARGS=" --git-repo ${CI_TARGET_DIR}/.git"
    else
        wget -O ${INSTALLER_PATH} ${CRUCIBLE_INSTALL_SRC}
        chmod +x ${INSTALLER_PATH}
    fi
    INSTALLER_CMD="${INSTALLER_PATH} --client-server-registry ${CONTAINER_REGISTRY} --client-server-tls-verify ${REGISTRY_TLS_VERIFY} --name nobody --email nobody@nobody.nobody.com --verbose ${INSTALLER_ARGS}"
    echo "Running: ${INSTALLER_CMD}"
    ${INSTALLER_CMD}
    RC=$?
    if [ ${RC} != 0 ]; then
        exit ${RC}
    fi

    popd > /dev/null
else
    echo "ERROR: Could not pushd to ~/"
    exit 1
fi
stop_github_group

start_github_group "CI Target Processing"
if [ "${CI_TARGET}" != "none" -a "${CI_TARGET_DIR}" != "none" ]; then
    if [ "${CI_TARGET}" != "crucible" ]; then
        echo "Handling --ci-target=${CI_TARGET} --ci-target-dir=${CI_TARGET_DIR}"

        if pushd /opt/crucible/subprojects > /dev/null; then
            STALE_LINK=$(find . -name ${CI_TARGET} -type l)

            if [ -z "${STALE_LINK}" ]; then
                echo "ERROR: Could not find --ci-target=${CI_TARGET}"
                exit 1
            fi

            if pushd $(dirname ${STALE_LINK}) > /dev/null; then
                echo "Found ${CI_TARGET} in $(pwd)"
                echo "Removing ${CI_TARGET}:"
                rm -v $(basename ${STALE_LINK})
                echo "Creating new symbolic link:"
                ln -sv ${CI_TARGET_DIR} $(basename ${STALE_LINK})
            else
                echo "ERROR: Could not pushd to $(dirname ${STALE_LINK})"
                exit 1
            fi
        else
            echo "ERROR: Could not pushd to /opt/crucible/subprojects"
            exit 1
        fi
    fi
else
    if [ "${CI_TARGET}" != "none" ]; then
        echo "ERROR: You must set --ci-target-dir when setting --ci-target"
        exit 1
    fi

    if [ "${CI_TARGET_DIR}" != "none" ]; then
        echo "ERROR: You must set --ci-target when setting --ci-target-dir"
        exit 1
    fi
fi
stop_github_group
