name: test-core-crucible-ci

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/test-core-crucible-ci
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      only-docs: ${{ steps.filter.outputs.only_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: tj-actions/changed-files@v47
        with:
          files: |
            LICENSE
            *.md
            **/*.md
            .github/rulesets/**
            .github/runners/**
            .github/workflows/faux-*.yaml
            .github/workflows/run-crucible-tracking.yaml
            .github/workflows/crucible-tracking.yaml
            .github/workflows/test-benchmark-crucible-ci.yaml
            .github/workflows/test-tool-crucible-ci.yaml
            .github/workflows/benchmark-crucible-ci.yaml
            .github/workflows/tool-crucible-ci.yaml
            docs/**
      - name: Display changes
        run: echo '${{ toJSON(steps.filter.outputs) }}' | jq .

  call-core-crucible-ci:
    needs: changes
    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.only-docs != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        repos:
        - subproject: "CommonDataModel"
          subproject_dir: "CommonDataModel"
          branch: "master"
          userenv_filter: "minimal"
    uses: ./.github/workflows/core-crucible-ci.yaml
    with:
      ci_target: "${{ matrix.repos.subproject }}"
      ci_target_dir: "${{ matrix.repos.subproject_dir }}"
      ci_target_branch: "${{ matrix.repos.branch }}"
      crucible_ci_test: "yes"
      crucible_ci_test_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
      userenv_filter: ${{ matrix.repos.userenv_filter }}
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}

  call-core-release-crucible-ci:
    needs: changes
    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.only-docs != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        repos:
        - subproject: "crucible"
          subproject_dir: "crucible"
          branch: "master"
          userenv_filter: "unique"
          force_controller_build: "yes"
        - subproject: "rickshaw"
          subproject_dir: "rickshaw"
          branch: "master"
          userenv_filter: "all"
          force_controller_build: "no"
    uses: ./.github/workflows/core-release-crucible-ci.yaml
    with:
      ci_target: "${{ matrix.repos.subproject }}"
      ci_target_dir: "${{ matrix.repos.subproject_dir }}"
      ci_target_branch: "${{ matrix.repos.branch }}"
      crucible_ci_test: "yes"
      crucible_ci_test_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
      userenv_filter: ${{ matrix.repos.userenv_filter }}
      force_controller_build: "${{ matrix.repos.force_controller_build }}"
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}

  faux-test-core-crucible-ci:
    needs: changes
    if: ${{ github.event_name != 'workflow_dispatch' && needs.changes.outputs.only-docs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "faux-test-core-crucible-ci-complete"

  test-core-crucible-ci-complete:
    runs-on: ubuntu-latest
    needs: [ call-core-crucible-ci, call-core-release-crucible-ci, faux-test-core-crucible-ci ]
    if: always()
    steps:
      - name: Check Results
        if: >-
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
        run: exit 1
      - run: echo "test-core-crucible-ci-complete"
